"""
one_d_visualize.py

Visualization for the V3 teaching-oriented 1D wave solver.

Important V3 outputs:
- 01_velocity_model.png shows a clearly variable 1D velocity profile.
- 05_seismic_record_time_receiver.png uses many receivers and receiver position on x-axis.
- 07_numerical_update_examples.png prints the finite-difference formula and actual numeric substitutions.
"""

from __future__ import annotations

from pathlib import Path
from typing import Sequence

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation, PillowWriter

from one_d_solver import SolverResult


def ensure_output_dir(output_dir: str | Path) -> Path:
    path = Path(output_dir)
    path.mkdir(parents=True, exist_ok=True)
    return path


def plot_velocity_model(result: SolverResult, output_dir: str | Path) -> Path:
    output_dir = ensure_output_dir(output_dir)
    path = output_dir / "01_velocity_model.png"

    fig, ax = plt.subplots(figsize=(10.5, 4.3))
    ax.plot(result.x, result.velocity, linewidth=2.4, label="Velocity v(x)")
    ax.axvline(result.x[result.source_index], linestyle="--", linewidth=2.0, label="Source")
    ax.axvline(result.x[result.calculation_index], linestyle="-.", linewidth=2.0, label="Selected calculation point")

    subset = np.linspace(0, len(result.receiver_xs) - 1, 7, dtype=int)
    for k, r in enumerate(subset):
        ax.axvline(result.receiver_xs[r], linestyle=":", alpha=0.50, label="Receivers" if k == 0 else None)

    ax.set_title("1D variable velocity model", fontsize=16)
    ax.set_xlabel("Position x (m)")
    ax.set_ylabel("Velocity v(x) (m/s)")
    ax.grid(True, alpha=0.3)
    ax.legend(loc="best")
    fig.tight_layout()
    fig.savefig(path, dpi=200)
    plt.close(fig)
    return path


def plot_source_signal(result: SolverResult, output_dir: str | Path) -> Path:
    output_dir = ensure_output_dir(output_dir)
    path = output_dir / "02_source_signal.png"

    fig, ax = plt.subplots(figsize=(10.5, 4.3))
    ax.plot(result.t, result.source_signal, linewidth=2.0)
    ax.set_title("Source time signal s(t)", fontsize=16)
    ax.set_xlabel("Time (s)")
    ax.set_ylabel("Source amplitude")
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    fig.savefig(path, dpi=200)
    plt.close(fig)
    return path


def plot_wave_snapshots(result: SolverResult, output_dir: str | Path, snapshot_steps: Sequence[int] | None = None) -> Path:
    output_dir = ensure_output_dir(output_dir)
    path = output_dir / "03_wavefield_snapshots.png"

    if snapshot_steps is None:
        snapshot_steps = [110, 210, 310, 430]

    ymax = np.percentile(np.abs(result.wavefield_history), 99.8)
    if ymax == 0:
        ymax = 1.0

    fig, axes = plt.subplots(len(snapshot_steps), 1, figsize=(11, 8.2), sharex=True)
    if len(snapshot_steps) == 1:
        axes = [axes]

    receiver_subset = np.linspace(0, len(result.receiver_xs) - 1, 5, dtype=int)

    for ax, step in zip(axes, snapshot_steps):
        step = int(np.clip(step, 0, len(result.t) - 1))
        ax.plot(result.x, result.wavefield_history[step], linewidth=1.8)
        ax.axvline(result.x[result.source_index], linestyle="--", label="Source")
        ax.axvline(result.x[result.calculation_index], linestyle="-.", label="Selected calculation point")
        for k, r in enumerate(receiver_subset):
            ax.axvline(result.receiver_xs[r], linestyle=":", alpha=0.45, label="Receivers" if k == 0 else None)
        ax.set_ylim(-1.15 * ymax, 1.15 * ymax)
        ax.set_title(f"Wavefield u(x,t) at t = {result.t[step]:.3f} s")
        ax.set_ylabel("Amplitude")
        ax.grid(True, alpha=0.3)

    axes[-1].set_xlabel("Position x (m)")
    axes[0].legend(loc="best")
    fig.tight_layout()
    fig.savefig(path, dpi=200)
    plt.close(fig)
    return path


def plot_receiver_traces(result: SolverResult, output_dir: str | Path) -> Path:
    output_dir = ensure_output_dir(output_dir)
    path = output_dir / "04_receiver_traces.png"

    selected = np.linspace(0, result.receiver_data.shape[1] - 1, 5, dtype=int)
    data = result.receiver_data[:, selected]
    max_abs = np.max(np.abs(data))
    if max_abs == 0:
        max_abs = 1.0
    offset = 1.7 * max_abs

    fig, ax = plt.subplots(figsize=(10.5, 5))
    for k, r in enumerate(selected):
        ax.plot(result.t, result.receiver_data[:, r] + k * offset, linewidth=1.5, label=f"x={result.receiver_xs[r]:.0f} m")

    ax.set_title("Selected receiver traces generated by the forward solver", fontsize=16)
    ax.set_xlabel("Time (s)")
    ax.set_ylabel("Amplitude with vertical offset")
    ax.grid(True, alpha=0.3)
    ax.legend(loc="best", title="Receiver")
    fig.tight_layout()
    fig.savefig(path, dpi=200)
    plt.close(fig)
    return path


def plot_seismic_record(result: SolverResult, output_dir: str | Path) -> Path:
    output_dir = ensure_output_dir(output_dir)
    path = output_dir / "05_seismic_record_time_receiver.png"

    vmax = np.percentile(np.abs(result.receiver_data), 99.5)
    if vmax == 0:
        vmax = 1.0

    extent = [result.receiver_xs[0], result.receiver_xs[-1], result.t[-1], result.t[0]]

    fig, ax = plt.subplots(figsize=(9.5, 6.2))
    im = ax.imshow(result.receiver_data, aspect="auto", extent=extent, vmin=-vmax, vmax=vmax, cmap="seismic")
    ax.axvline(result.x[result.source_index], linestyle="--", color="black", alpha=0.7, label="Source")
    ax.axvline(result.x[result.calculation_index], linestyle="-.", color="black", alpha=0.7, label="Selected calculation point")

    ax.set_title("Forward-generated seismic record: time × receiver position", fontsize=16)
    ax.set_xlabel("Receiver position x (m)")
    ax.set_ylabel("Time (s)")
    ax.legend(loc="upper right")
    cbar = fig.colorbar(im, ax=ax)
    cbar.set_label("Recorded amplitude")
    fig.tight_layout()
    fig.savefig(path, dpi=200)
    plt.close(fig)
    return path


def plot_wavefield_image(result: SolverResult, output_dir: str | Path) -> Path:
    output_dir = ensure_output_dir(output_dir)
    path = output_dir / "06_full_wavefield_time_position.png"

    vmax = np.percentile(np.abs(result.wavefield_history), 99.5)
    if vmax == 0:
        vmax = 1.0

    extent = [result.x[0], result.x[-1], result.t[-1], result.t[0]]

    fig, ax = plt.subplots(figsize=(10.5, 6.3))
    im = ax.imshow(result.wavefield_history, aspect="auto", extent=extent, vmin=-vmax, vmax=vmax, cmap="seismic")
    ax.axvline(result.x[result.source_index], linestyle="--", color="black", alpha=0.75, label="Source")
    ax.axvline(result.x[result.calculation_index], linestyle="-.", color="black", alpha=0.75, label="Selected calculation point")

    subset = np.linspace(0, len(result.receiver_xs) - 1, 7, dtype=int)
    for k, r in enumerate(subset):
        ax.axvline(result.receiver_xs[r], linestyle=":", color="black", alpha=0.35, label="Receivers" if k == 0 else None)

    ax.set_title("Forward wave propagation in a variable 1D velocity model", fontsize=16)
    ax.set_xlabel("Position x (m)")
    ax.set_ylabel("Time (s)")
    ax.legend(loc="best")
    cbar = fig.colorbar(im, ax=ax)
    cbar.set_label("Wave amplitude")
    fig.tight_layout()
    fig.savefig(path, dpi=200)
    plt.close(fig)
    return path


def _format_update_text(ex: dict) -> str:
    return "\n".join([
        rf"Selected point: $x_i={ex['x']:.1f}\ \mathrm{{m}}$",
        rf"$v_i={ex['v']:.1f}\ \mathrm{{m/s}},\quad \Delta t={ex['dt']:.4f}\ \mathrm{{s}},\quad \Delta x={ex['dx']:.1f}\ \mathrm{{m}}$",
        rf"$\alpha_i=(v_i\Delta t/\Delta x)^2={ex['alpha']:.6f}$",
        "",
        rf"$u_i^{{n-1}}={ex['u_prev_i']:+.6e}$",
        rf"$u_{{i-1}}^n={ex['u_curr_im1']:+.6e}$",
        rf"$u_i^n={ex['u_curr_i']:+.6e}$",
        rf"$u_{{i+1}}^n={ex['u_curr_ip1']:+.6e}$",
        "",
        rf"$u_{{i+1}}^n-2u_i^n+u_{{i-1}}^n={ex['curvature']:+.6e}$",
        rf"$\alpha_i\,\mathrm{{curvature}}={ex['alpha_times_curvature']:+.6e}$",
        rf"$s_i^n={ex['source_term']:+.6e}$",
        "",
        rf"$u_i^{{n+1}}$ before damping $={ex['u_next_after_source']:+.6e}$",
        rf"damping factor $={ex['damping_factor']:.6f}$",
        rf"$u_i^{{n+1}}$ after damping $={ex['u_next_after_damping']:+.6e}$",
    ])


def plot_numerical_update_examples(
    result: SolverResult,
    output_dir: str | Path,
    filename: str = "07_numerical_update_examples.png",
    title: str = "Concrete finite-difference calculations at one selected receiver/grid point",
) -> Path:
    output_dir = ensure_output_dir(output_dir)
    path = output_dir / filename

    examples = result.calculation_examples[:3]
    if not examples:
        raise ValueError("No calculation examples were saved.")

    ymax = np.percentile(np.abs(result.wavefield_history), 99.8)
    if ymax == 0:
        ymax = 1.0

    fig, axes = plt.subplots(len(examples), 2, figsize=(18, 5.2 * len(examples)), gridspec_kw={"width_ratios": [1.05, 1.25]})
    if len(examples) == 1:
        axes = np.array([axes])

    for row, ex in enumerate(examples):
        ax_wave = axes[row, 0]
        ax_text = axes[row, 1]
        i = ex["index"]
        step = ex["step"]
        u = ex["u_curr_array"]

        # Zoom around the selected point so i-1, i, i+1 can be seen clearly.
        half_width = 170.0
        xmin = max(result.x[0], ex["x"] - half_width)
        xmax = min(result.x[-1], ex["x"] + half_width)
        mask = (result.x >= xmin) & (result.x <= xmax)

        ax_wave.plot(result.x[mask], u[mask], linewidth=2.1, color="tab:blue")
        ax_wave.axvline(result.x[i], linestyle="-.", color="black", linewidth=1.6, label="selected point i")

        xs = [result.x[i - 1], result.x[i], result.x[i + 1]]
        ys = [u[i - 1], u[i], u[i + 1]]
        ax_wave.scatter(xs, ys, s=95, zorder=5, color=["tab:orange", "tab:red", "tab:orange"], edgecolor="black", linewidth=0.7)
        for xx, yy, lab in zip(xs, ys, [r"$i-1$", r"$i$", r"$i+1$"]):
            ax_wave.annotate(lab, xy=(xx, yy), xytext=(0, 15), textcoords="offset points", ha="center", fontsize=13)

        ax_wave.set_title(f"Layered reflection case: local stencil at n={step}, t={ex['time']:.3f} s")
        ax_wave.set_xlabel("Position x (m)")
        ax_wave.set_ylabel("Current amplitude u^n")
        ax_wave.grid(True, alpha=0.3)
        ax_wave.legend(loc="best")
        ax_wave.set_ylim(-1.15 * ymax, 1.15 * ymax)

        ax_text.axis("off")
        ax_text.text(
            0.02,
            0.98,
            r"$u_i^{n+1}=2u_i^n-u_i^{n-1}+\alpha_i(u_{i+1}^n-2u_i^n+u_{i-1}^n)+s_i^n$",
            va="top",
            ha="left",
            fontsize=16,
        )
        ax_text.text(
            0.02,
            0.80,
            _format_update_text(ex),
            va="top",
            ha="left",
            fontsize=12.2,
            linespacing=1.55,
            bbox=dict(boxstyle="round,pad=0.75", facecolor="white", edgecolor="0.72"),
        )

    fig.suptitle(title, fontsize=20, y=0.997)
    fig.tight_layout()
    fig.savefig(path, dpi=200)
    plt.close(fig)
    return path


def animate_wavefield(result: SolverResult, output_dir: str | Path, every: int = 3, fps: int = 25) -> Path:
    output_dir = ensure_output_dir(output_dir)
    path = output_dir / "08_wave_propagation_animation.gif"

    ymax = np.percentile(np.abs(result.wavefield_history), 99.8)
    if ymax == 0:
        ymax = 1.0

    fig, ax = plt.subplots(figsize=(10.5, 4.2))
    line, = ax.plot([], [], linewidth=1.8)
    time_text = ax.text(0.02, 0.90, "", transform=ax.transAxes)
    ax.axvline(result.x[result.source_index], linestyle="--", label="Source")
    ax.axvline(result.x[result.calculation_index], linestyle="-.", label="Selected calculation point")
    subset = np.linspace(0, len(result.receiver_xs) - 1, 7, dtype=int)
    for k, r in enumerate(subset):
        ax.axvline(result.receiver_xs[r], linestyle=":", alpha=0.45, label="Receivers" if k == 0 else None)

    ax.set_xlim(result.x[0], result.x[-1])
    ax.set_ylim(-1.15 * ymax, 1.15 * ymax)
    ax.set_xlabel("Position x (m)")
    ax.set_ylabel("Wave amplitude")
    ax.set_title("1D wave propagation in a variable velocity model")
    ax.grid(True, alpha=0.3)
    ax.legend(loc="best")

    frames = list(range(0, len(result.t), every))

    def init():
        line.set_data([], [])
        time_text.set_text("")
        return line, time_text

    def update(frame):
        line.set_data(result.x, result.wavefield_history[frame])
        time_text.set_text(f"t = {result.t[frame]:.3f} s")
        return line, time_text

    anim = FuncAnimation(fig, update, frames=frames, init_func=init, blit=True)
    anim.save(path, writer=PillowWriter(fps=fps))
    plt.close(fig)
    return path


def make_all_visualizations(result: SolverResult, output_dir: str | Path) -> list[Path]:
    return [
        plot_velocity_model(result, output_dir),
        plot_source_signal(result, output_dir),
        plot_wave_snapshots(result, output_dir),
        plot_receiver_traces(result, output_dir),
        plot_seismic_record(result, output_dir),
        plot_wavefield_image(result, output_dir),
        plot_numerical_update_examples(result, output_dir),
        animate_wavefield(result, output_dir),
    ]
